import Head from 'next/head';
import { useAuth } from '../src/hooks/useAuth';
import { useEffect, useState } from 'react';

import styles from '../styles/Home.module.css';
import { useGoogleAuth } from '../src/hooks/useGoogleAuth';
import Image from 'next/image';
import { getRemoteConfigValue, initFirebase } from '../src/services/firebase';

export default function Home() {
  const [user, setUser] = useState();
  const [color, setColor] = useState();

  useEffect(() => {
    const initHomePage = () => {
      const saveUserLocalData = () => {
        const userLocalData = JSON.parse(localStorage.getItem('user-data'));
        if (!userLocalData) {
          return
        }
        
        const setMainColor = async () => {
          const configColor = await getRemoteConfigValue("color")
          .then((res) => res._value);

          setColor(configColor);
        }

        setMainColor()
        setUser(userLocalData)
      }
      
      initFirebase()
      saveUserLocalData()
    }
    
    return initHomePage()
  }, [])  

  const authUserWithEmailAndPassword = async (e) => {
    const { userCredentials, error } = await useAuth(getFormData(e));
    if (error === "email already in use") {
      console.log("error")
      return
    }
    
    if (userCredentials) {
      localStorage.setItem('access-token', userCredentials.accessToken)
      return setUser(userCredentials)
    }
  }
  
  const getFormData = (e) => {
    e.preventDefault();
    const form = e.target;
    return { email: form.email.value, password: form.password.value }
  }
  
  const authWithGoogle = async () => {
    const { user } = await useGoogleAuth();
    setUser(user)
    localStorage.setItem('user-data', JSON.stringify({ displayName, email, photoURL }))
  }
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {user ?
          (
            <>
            <h1>{color} {user.displayName}</h1>
            <h2>{user.email}</h2>
            <Image 
              src={user.photoURL} 
              alt={user.displayName} 
              width={300}
              height={300}
            />
            </>
          ) : (
            <>
            <form onSubmit={authUserWithEmailAndPassword}>
              <input name="email"/>
              <input name="password"/>
              <button type='submit'>Auth</button>
            </form>
    
            <button onClick={authWithGoogle}>Auth with Google</button>
            </>
          )
        }
      </main>
    </div>
  );
}
